# Generated by Django 5.2 on 2026-03-05 06:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctorsapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="profile_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
