# Generated by Django 5.2 on 2026-03-11 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctorsapp", "0004_cliniclisting_clinicservice"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinic",
            name="admin",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_superuser": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admin_clinics",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="clinic",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_clinics",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="clinic",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_clinics",
                to="doctorsapp.doctor",
            ),
        ),
        migrations.AlterField(
            model_name="clinic",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="clinic_images/"),
        ),
        migrations.AlterField(
            model_name="clinic",
            name="map_marker",
            field=models.ImageField(blank=True, null=True, upload_to="map_markers/"),
        ),
        migrations.AlterField(
            model_name="galleryimage",
            name="image",
            field=models.ImageField(default=1, upload_to="clinic_gallery/"),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="clinic",
            unique_together={("name", "city", "admin")},
        ),
    ]
