# Generated by Django 5.2 on 2026-03-11 08:31

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctorsapp", "0005_clinic_admin_clinic_user_alter_clinic_doctor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_clinic",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                default=1, max_length=254, unique=True, verbose_name="email address"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="profile_image"
            ),
        ),
    ]
