# Generated by Django 5.2 on 2026-03-11 09:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctorsapp", "0006_user_is_clinic_alter_user_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinic",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="profile_image"
            ),
        ),
        migrations.AlterField(
            model_name="clinic",
            name="map_marker",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="profile_image"
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="profile_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="profile_image"
            ),
        ),
        migrations.AlterField(
            model_name="galleryimage",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="profile_image"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="profile_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="profile_image"
            ),
        ),
    ]
