# Generated by Django 5.2 on 2026-03-11 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctorsapp", "0007_alter_clinic_image_alter_clinic_map_marker_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinic",
            name="admin",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_clinic": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admin_clinics",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
