# Generated by Django 5.2 on 2026-03-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctorsapp", "0008_alter_clinic_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinic",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
