# Generated by Django 5.2 on 2026-03-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctorsapp", "0009_alter_clinic_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="appointment_type",
            field=models.CharField(
                blank=True, default="consultation", max_length=50, null=True
            ),
        ),
    ]
