# Generated by Django 5.2 on 2026-03-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctorsapp", "0010_alter_appointment_appointment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Pending", "Pending"),
                    ("Accepted", "Accepted"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="total_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
    ]
