# Generated by Django 5.2 on 2026-03-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctorsapp", "0011_alter_appointment_amount_alter_appointment_fee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="prescription",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="prescription_file",
            field=models.FileField(blank=True, null=True, upload_to="prescriptions/"),
        ),
    ]
